export default {
  'GET_FILE_LIST': 'GET_FILE_LIST',
  'FILE_LIST_RECEIVED': 'GET_FILE_RECEIVED',
  'GET_FILE_LIST_ERROR': 'GET_FILE_LIST_ERROR',
  'SCAN_IMAGE_FILE':'SCAN_IMAGE_FILE',
  'IMAGE_FILE_SCANNED':'IMAGE_FILE_SCANNED',
  'SCAN_IMAGE_FILE_FAILED':'SCAN_IMAGE_FILE_FAILED',
  'UPLOAD_TO_GW': 'UPLOAD_TO_GW',
  'UPLOAD_TO_GW_SUCCESS': 'UPLOAD_TO_GW_SUCCESS',
  'UPLOAD_TO_GW_FAILED': 'UPLOAD_TO_GW_FAILED'
}